---
title: "Data Sources"
author: "Tiny Blocks"
date: "10/27/2020"
output: 
  html_document:
    theme: spacelab 
    toc: true
    toc_depth: 5
    toc_float: true
    code_folding: show
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

# Data Sources

<br>

* Footpaths to calculate network distance -- walking distance (6.15km/h walking speed)
* 2019 subzone data

<br>

| Data | Description | Geometry | Format | Source |
|------|-------------|----------|--------|--------|
| HDB Flats | Location of HDB flats, retrieved from OpenStreetMap | Point | Shapefile | OpenStreetMap |
| Schools | Location of schools, geocoded from CSV | Point | Shapefile | [data.gov.sg](https://data.gov.sg/dataset/school-directory-and-information) |
| Population | Resident data by planning subzone, age group, sex and type of dwelling | NA | CSV | [Department of Statistics Singapore](https://www.singstat.gov.sg/find-data/search-by-theme/population/geographic-distribution/latest-data) |
| Pre-Schools | Location of childcare centres and kindergartens | Point | KML | [data.gov.sg](https://data.gov.sg/dataset/pre-schools-location) |
| Nature Areas | Boundary of nature reserves, national parks and nature areas | Polygon | KML | [data.gov.sg](https://data.gov.sg/dataset/master-plan-2019-sdcp-nature-boundary-layer) |
| Parks | Boundary of parks managed by NParks | Polygon | KML | [data.gov.sg](https://data.gov.sg/dataset/nparks-parks) |
| Roads | Road network | Polyline | KML | [data.gov.sg](https://data.gov.sg/dataset/master-plan-2019-road-name-layer?resource_id=667b3f04-38d7-4be1-bb0e-6aa4141a03ee) |
