---
title: "Data Preparation"
author: "Tiny Blocks"
date: "10/22/2020"
output:
  html_document:
    theme: spacelab 
    toc: true
    toc_depth: 5
    toc_float: true
    code_folding: show
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
packages = c('tmap', 'SpatialAcc', 'sf', 'ggstatsplot', 'tidyverse')

for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

# Importing Geospatial Data
```{r}
na_validity_check <-function(input){
  print("Check for NA...")
  print(input[rowSums(is.na(input))!=0,])
  test <- st_is_valid(input,reason=TRUE)
  print("Check for invalid geometry...")
  length(which(test!= "Valid Geometry"))
}
```

```{r message=FALSE, warning=FALSE}
mpsz = st_read(dsn = "data/geospatial", layer = "subzone")
cib = st_read(dsn = "data/geospatial", layer = "cib_gardens")
comm_club = st_read(dsn = "data/geospatial/community_clubs.kml")
comm_use_site = st_read(dsn = "data/geospatial/community_use_sites.kml")
dus_sports_facilities = st_read(dsn = "data/geospatial", layer = "dus_school_sports_facilities")
nature_areas = st_read(dsn = "data/geospatial/nature_areas.kml")
np_activity_area = st_read(dsn = "data/geospatial/nparks_activity_area.kml")
np_parks = st_read(dsn = "data/geospatial/nparks_parks.kml")
np_play_fitness = st_read(dsn = "data/geospatial/nparks_play_fitness_equipment.kml")
park_loop = st_read(dsn = "data/geospatial/park_connector_loop.kml")
preschools = st_read(dsn = "data/geospatial/preschools.kml")
schools = st_read(dsn = "data/geospatial", layer = "schools")
student_care = st_read(dsn = "data/geospatial/student_care.kml")
sportsg_facilities= st_read(dsn = "data/geospatial/sportsg_sports_facilities.kml")
watersports_facilities = st_read(dsn = "data/geospatial", layer = "water_sport_facilities")
```

```{r}
na_validity_check(mpsz)
```

```{r}
hdb <- read_csv('data/aspatial/hdb.csv')
hdb <- hdb %>%
  st_as_sf(coords = c('longtitude', 'latitude'),
           crs = 3414)
```

```{r}
st_crs(hdb)
```

```{r}
population <- read_csv('data/aspatial/population.csv')
```

```{r}

```




